/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_logicway_grpcclient_lib_JNILib */

#ifndef _Included_com_logicway_grpcclient_lib_JNILib
#define _Included_com_logicway_grpcclient_lib_JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_logicway_grpcclient_lib_JNILib
 * Method:    getAndroidId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_logicway_grpcclient_lib_JNILib_getAndroidId
  (JNIEnv *, jobject);

/*
 * Class:     com_logicway_grpcclient_lib_JNILib
 * Method:    getGsfId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_logicway_grpcclient_lib_JNILib_getGsfId
  (JNIEnv *, jobject);

/*
 * Class:     com_logicway_grpcclient_lib_JNILib
 * Method:    getFingerprint
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_logicway_grpcclient_lib_JNILib_getFingerprint
  (JNIEnv *, jobject);

/*
 * Class:     com_logicway_grpcclient_lib_JNILib
 * Method:    getBase64FromIdsHashes
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_logicway_grpcclient_lib_JNILib_getBase64FromIdsHashes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
